<?php require './app/templates/header.phtml' ?>

<h4 class="ps-2 fw-bold">Detalle del Genero:</h4>
<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <b><?= $genre->nombre ?></b>
            | <?= $genre->id ?>
            | Número de tracks: <?= $tracks ?>
        </div>
    </li>
    <?php foreach ($songs as $item) : ?>
        <li class="list-group-item item-task">
            <div>
                <b>Artista: <?= $item->artist ?></b>
                <b>| Cancion: <a href="songs/<?= $item->id ?>"><?= $item->title ?></a><b>
                | Duración: <?= $item->duration ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php require './app/templates/footer.phtml' ?>