<?php require './app/templates/header.phtml' ?>

<h4 class="ps-2 fw-bold">Detalle de Canción:</h4>
<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <b><?= $song->title ?></b>
            | <a href="genres/<?= $genre->genre_id ?>"><?= $genre->nombre?></a>
            | <?= $song->artist ?>
            | Duración: <?= $song->duration ?>
            <iframe style="border-radius:12px" src="<?= $song->link ?>" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            </h5>Lirica de la Cancion:<br/> <?= $song->lyrics ?></h5>
        </div>
    </li>
</ul>

<?php require './app/templates/footer.phtml' ?>