<?php require './app/templates/header.phtml' ?>

<h2 class="ps-2 fw-bold">Detalles del Genero: <?= $genre->nombre ?></h2>
<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <b> | ID: <?= $genre->id ?>
            | Año de Creacion: <?= $genre->año ?>
        </div>
        <div>
            <b> Historia del Genero Musical: </b>
            <span><?= $genre->descripcion ?></span>
        </div>
    </li>
    <?php foreach ($songs as $item) : ?>

    <h3>Cantidad de Canciones del Genero: <?= $tracks ?> </h3>
        <li class="list-group-item item-task">
            <div>
                <b>Artista: <?= $item->artist ?></b>
                <b>| Cancion: <a href="songs/<?= $item->id ?>"><?= $item->title ?></a><b>
                | Duración: <?= $item->duration ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php require './app/templates/footer.phtml' ?>