<?php require './app/templates/header.phtml' ?>

<h4 class="ps-2 fw-bold">Detalle del Genero:</h4>
<ul class="list-group">
    <li class="list-group-item item-task">
        <div>
            <b><?= $genre->nombre ?></b>
            | <?= $genre->artista ?>
            | Año: <?= $genre->anio ?>
            | Discográfica: <?= $genre->discografica ?>
            | Duración: <?= $duracion ?>
            | Número de tracks: <?= $tracks ?>
        </div>
    </li>
    <?php foreach ($songs as $item) : ?>
        <li class="list-group-item item-task">
            <div>
                <b><?= $item->track ?></b> 
                | <a href="songs/<?= $item->cancion_id ?>"><?= $item->cancion_nombre ?></a>
                | Duración: <?= $item->duracion ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>

<?php require './app/templates/footer.phtml' ?>