</main>
<!-- fin main container -->

<!-- main footer -->
<footer class="d-flex flex-wrap justify-content-center align-items-center py-3 my-4 border-top">
<div class="contenido-principal">
<div class="container">

    <!-- Imagen del Dragón -->
    <img src="..\web2-tpe-master\img\logo2.png" alt="Dragón rojo" class="imagen-dragon" id="dragon" onclick="reproducirRugido()">

    <!-- Audio del rugido -->
    <audio id="rugido-dragon">
        <source src="..\web2-tpe-master\audio\rugido.mp3" type="audio/mpeg">
    </audio>
</div>

<!-- JavaScript para manejar la reproducción del sonido -->
<script>
    function reproducirRugido() {
        var rugido = document.getElementById("rugido-dragon");
        rugido.play();
    }
</script>
</div>
</div>
      <div class="align-items-center">
        <span  id="miSpan">2024 TUDAI, UNICEN</span>
      </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>