<form action="genres-save" method="POST" class="my-4">
    <div class="row">
        <div class="form-group">
            <label>Genero</label>
            <input required name="nombre" type="text" placeholder="Ingrese el nombre del nuevo genero" class="form-control">
        </div>

        <div class="form-group">
            <label>Año de Creacion del Genero:</label>
            <input required name="anio" type="number" placeholder="Ingrese el año de creacion del genero" class="form-control"> 
        </div>
    </div>

    <div class="form-group">
        <label for="descripcion">Historia del Genero:</label>
        <textarea required name="descripcion" placeholder="Ingrese la descripcion historica del genero" class="form-control" rows="5"></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>