<form action="genres-save/<?= $genre->id ?>" method="POST" class="my-4">
    <div class="row">
        <div class="form-group">
            <label>Editando Genero:</label>
            <input required name="nombre" type="text" placeholder="Ingrese el nombre del Genero" class="form-control" value="<?= $genre->nombre ?>" >
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Guardar Cambios</button>
    <a type="button" href="genres" class="btn btn-danger mt-2">Cancelar Edición</a>
</form>