<form action="songs-save/<?= $song->id?>" method="POST" class="my-4">
    <div class="row">
        <div class="form-group">
            <label>Editando Canción:</label>
            <input required name="cancion" type="text" placeholder="Ingrese el nuevo nombre de la canción" class="form-control" value="<?= $song->title?>" >
        </div>
        <div class="form-group">
            <label>Editando Artista:</label>
            <input required name="cancion" type="text" placeholder="Ingrese el nuevo nombre del/la artista" class="form-control" value="<?= $song->artist?>" >
        </div>
        <div class="form-group">
            <label>Álbum</label>
            <select required name="genre" class="form-control">
                <option disabled>Seleccione el álbum</option>
                <?php foreach ($genres as $item) : ?>
                    <option 
                    value="<?= $item->id ?>"
                    <?php if ($item->id == $song->artist): ?> selected <?php endif ?>>
                    <?= $item->nombre ?> 
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class=row>
        <div class="col-6">
            <label>Duración</label>
            <input required name="duracion" type="text" placeholder="Ingrese la nueva duración de la cancion" class="form-control" value="<?= $song->duration ?>">
        </div>
    
        <div class="col-6">
            <label>Url:</label>
            <input required name="link" type="text" placeholder="Ingrese el nuevo URL de la cancion" class="form-control" value="<?= $song->link ?>">
        </div>

        <div class="form-group">
            <label for="lyrics">Letra de la Canción:</label>
            <textarea required name="lyrics" placeholder="Ingrese la nueva lírica/letra de la canción" class="form-control" rows="5"><?= $song->lyrics ?></textarea>
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Guardar Cambios</button>
    <a type="button" href="songs" class="btn btn-danger mt-2">Cancelar Edicion</a>
</form>