<form action="songs-save" method="POST" class="my-4">
    <div class="row">
        <div class="form-group">
            <label>Canción</label>
            <input required name="cancion" type="text" placeholder="Ingrese el nombre de la canción" class="form-control">
        </div>
        <div class="form-group">
            <label>Artista:</label>
            <input required name="artista" type="text" placeholder="Ingrese el nombre del/la artista" class="form-control">
        </div>
        <div class="form-group">
            <label>Genero de la Cancion:</label>
            <select required name="genero" class="form-control">
                <option selected disabled>Seleccione el Genero de la Cancion</option>
                <?php foreach ($genres as $item) : ?>
                    <option value="<?= $item->id ?>"><?= $item->nombre ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <div class=row>
        <div class="col-6">
            <label>Duración:</label>
            <input required name="duracion" type="text" placeholder="Ingrese la duración de la cancion" class="form-control">
        </div>

        <div class="col-6">
            <label>Url:</label>
            <input required name="link" type="text" placeholder="Ingrese la url de la cancion(Spotify solamente)" class="form-control">
        </div>

        <div class="form-group">
            <label for="lyrics">Letra de la Canción:</label>
            <textarea required name="lyrics" placeholder="Ingrese la lírica/letra de la canción" class="form-control" rows="5"></textarea>
        </div>
    </div>
    
    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>