<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<h4 class="ps-2 fw-bold">Canciones:</h4>
<table class="table">
    <thead>
        <tr>
            <th>Canción</th>
            <th>Artist</th>
            <th>Duración</th>
            <th>Genero</th>
            <?php if ($this->session) : ?>
                <th>Acciones:</th>
            <?php endif ?>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($songs as $item) : ?>
            <tr>
                <th><a href="songs/<?= $item->id?>"><?= $item->title ?></a></th>
                <td><?= $item->artist ?></a></td>
                <td><?= $item->duration ?></td>
                <td><?= $item->genre_name ?></td>
                <?php if ($this->session) : ?>
                <td>
                    <a href="songs-edit/<?= $item->id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                    <a href="songs-remove/<?= $item->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>
            </tr>
            <?php endif ?>
            <?php endforeach ?>
        </tbody>
</table>

<?php require './app/templates/footer.phtml' ?>