<?php require './app/templates/header.phtml' ?>

<?php if ($this->session) : require $form; endif ?>

<h4 class="ps-2 fw-bold">Elije un Generos:</h4>
<table class="table">
    <thead>
        <tr>
            <th>Nombre de Genero</th>
            <th>ID:</th>
            <th>Acciones:</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($genres as $item) : ?>
            <tr>
                <th><a href="genres/<?= $item->id ?>"><?= $item->nombre ?></a></th>
                <td><?= $item->id ?></td>
                <?php if ($this->session) : ?>
                <td>
                    <a href="genres-edit/<?= $item->id ?>" type="button" class='btn btn-warning ml-auto'>Editar</a>
                    <a href="genres-remove/<?= $item->id ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                </td>
            </tr>
            <?php endif ?>
            <?php endforeach ?>
        </tbody>
</table>

<?php require './app/templates/footer.phtml' ?>